rule all:
    input: 
        "analysis/baselines.png",
        "analysis/dirty_image.png"        

rule baselines:
    input: "data/mock_data.npz", "src/plot_baselines.py"
    output: "analysis/baselines.png"
    shell: "python src/plot_baselines.py {output}"

rule dirty_image:
    input: "data/mock_data.npz", "src/dirty_image.py"
    output: "analysis/dirty_image.png"
    shell: "python src/dirty_image.py {output}"


# python src/sgd.py --tensorboard-log-dir=runs/exp0 --save-checkpoint=checkpoints/0.pt 
# python src/sgd.py --tensorboard-log-dir=runs/exp1 --load-checkpoint=checkpoints/0.pt --save-checkpoint=checkpoints/1.pt
# python src/sgd.py --tensorboard-log-dir=runs/exp2 --load-checkpoint=checkpoints/1.pt --save-checkpoint=checkpoints/2.pt --epochs=50
# python src/sgd.py --tensorboard-log-dir=runs/exp3 --load-checkpoint=checkpoints/2.pt --save-checkpoint=checkpoints/3.pt --epochs=50 --lr 1e4

# python src/sgd.py --tensorboard-log-dir=runs/exp5 --save-checkpoint=checkpoints/5.py --epochs=50
# python src/sgd.py --tensorboard-log-dir=runs/exp6 --save-checkpoint=checkpoints/6.py --epochs=10 --batch-size=1000

# python src/sgd.py --tensorboard-log-dir=runs/ent0 --epochs=15 --batch-size=5000 --lam-ent=1e-5 --epochs=50 --save-checkpoint=checkpoints/ent0.pt
# low of 7.8e-5 validation loss 
# python src/sgd.py --tensorboard-log-dir=runs/ent1 --epochs=15 --batch-size=5000 --lam-ent=1e-5 --epochs=50 --save-checkpoint=checkpoints/ent1.pt --load-checkpoint=checkpoints/ent0.pt

# python src/sgd.py --tensorboard-log-dir=runs/ent2 --epochs=15 --batch-size=10000 --lam-ent=1e-6 --epochs=20 --log-interval=2 --save-checkpoint=checkpoints/ent0.pt 
# python src/sgd.py --tensorboard-log-dir=runs/ent3 --epochs=15 --batch-size=10000 --lam-ent=1e-6 --epochs=20 --log-interval=2 --save-checkpoint=checkpoints/ent1.pt --load-checkpoint=checkpoints/ent0.pt

# python src/sgd.py --tensorboard-log-dir=runs/ent4 --epochs=15 --batch-size=10000 --lam-ent=5e-6 --epochs=20 --log-interval=2 --save-checkpoint=checkpoints/ent0.pt
# python src/sgd.py --tensorboard-log-dir=runs/ent5 --epochs=50 --batch-size=10000 --lam-ent=5e-6 --epochs=20 --log-interval=2 --save-checkpoint=checkpoints/ent1.pt --load-checkpoint=checkpoints/ent0.pt
# python src/sgd.py --tensorboard-log-dir=runs/ent6 --epochs=80 --batch-size=10000 --lam-ent=5e-6 --epochs=20 --log-interval=2 --save-checkpoint=checkpoints/ent2.pt --load-checkpoint=checkpoints/ent1.pt
# python src/sgd.py --tensorboard-log-dir=runs/ent7 --epochs=100 --batch-size=10000 --lam-ent=5e-6 --epochs=20 --log-interval=2 --save-checkpoint=checkpoints/ent3.pt --load-checkpoint=checkpoints/ent2.pt
# python src/sgd.py --tensorboard-log-dir=runs/ent8 --epochs=100 --batch-size=10000 --lam-ent=5e-6 --log-interval=2 --save-checkpoint=checkpoints/ent5.pt --load-checkpoint=checkpoints/ent4.pt



# trying with adamw
# no regularization
# python src/sgd.py --tensorboard-log-dir=runs/nolam0 --epochs=10 --log-interval=1 --save-checkpoint=checkpoints/nolam0.pt --lr 5e-2
# min validation: 9.0e-5, but not perfectly captured

# maximum entropy
# lam = 1e-5
# python src/sgd.py --tensorboard-log-dir=runs/lam1e-5_0 --epochs=50 --log-interval=1 --save-checkpoint=checkpoints/lam1e-5_0.pt --lr 5e-2 --lam-ent=1e-5
# python src/sgd.py --tensorboard-log-dir=runs/lam1e-5_1 --epochs=50 --log-interval=1 --save-checkpoint=checkpoints/lam1e-5_1.pt --load-checkpoint=checkpoints/lam1e-5_0.pt --lr 1e-1 --lam-ent=1e-5
# min validation: 7.33e-5, though significant variation to 8.2e-5, suggesting that image is
# changing significantly as LR might be too high, perhaps?