rule all:
    input: 
        "analysis/baselines.png",
        "analysis/dirty_image.png"        

rule baselines:
    input: "data/mock_data.npz", "src/plot_baselines.py"
    output: "analysis/baselines.png"
    shell: "python src/plot_baselines.py {output}"

rule dirty_image:
    input: "data/mock_data.npz", "src/dirty_image.py"
    output: "analysis/dirty_image.png"
    shell: "python src/dirty_image.py {output}"


# some initial attempts
# python src/sgd.py --tensorboard-log-dir=runs/exp0 --save-checkpoint=checkpoints/0.pt --lr 1e-2 --FWHM 0.05 --epochs=50
# python src/sgd.py --tensorboard-log-dir=runs/exp1 --load-checkpoint=checkpoints/0.pt --save-checkpoint=checkpoints/1.pt --lr 1e-1 --FWHM 0.05 --epochs=30
# python src/sgd.py --tensorboard-log-dir=runs/exp2 --load-checkpoint=checkpoints/1.pt --save-checkpoint=checkpoints/2.pt --lr 4e-1 --FWHM 0.05 --epochs=50


# python src/sgd.py --tensorboard-log-dir=runs/ent0 --load-checkpoint=checkpoints/2.pt --save-checkpoint=checkpoints/ent0.pt --lr 1e-1 --FWHM 0.05 --epochs=50 --lam-ent=1e-5


# vary fixed FWHM and entropy regularization to find best validation score.